// BIND configuration file format
// authoritative primary named.conf file
// options clause defining the server-wide properties

// Two corporate subnets we wish to allow queries from
// defined in an acl clause, networks is the name of the ACL that can be changed

acl networks {
  10.0.0.0/8;                   // careful with this if running in docker, it will often be SNATted into the docker network
};

options {
    directory "/var/cache/bind";

    listen-on { any; };
    listen-on-v6 { none; };


    recursion yes;              // Allow recursion
    allow-recursion { any; };
    allow-query { any; };       // referenced the acl created above

    dnssec-validation no;


    forwarders {                //define forwaders
        8.8.8.8;
        1.1.1.1;
    };
};


zone "." {
    type hint;
    file "/usr/share/dns/root.hints";
};

zone "sargon.local" {
    type primary;
    file "/etc/bind/zones/db.sargon.local";
};


// Reverse lookup zone commented out
// zone "127.in-addr.arpa" {
//    type primary;
//    file "/etc/bind/zones/db.127";
// };
