#################################################
# Sample OpenVPN 2.6 config file for            #
# multi-client server.                          #
#                                               #
# This file is for the server side              #
# of a many-clients <-> one-server              #
# OpenVPN configuration.                        #
#                                               #
# OpenVPN also supports                         #
# single-machine <-> single-machine             #
# configurations (See the Examples page         #
# on the web site for more info).               #
#                                               #
# This config should work on Windows            #
# or Linux/BSD systems.  Remember on            #
# Windows to quote pathnames and use            #
# double backslashes, e.g.:                     #
# "C:\\Program Files\\OpenVPN\\config\\foo.key" #
#                                               #
# Comments are preceded with '#' or ';'         #
#################################################

############################################################################### General Settings
# Which local IP address should OpenVPN
# listen on? (optional)
;local a.b.c.d

# Which TCP/UDP port should OpenVPN listen on?
port 1194

# TCP or UDP server?
;proto tcp
proto udp

;dev tap
dev tun

# It's a good idea to reduce the OpenVPN
# daemon's privileges after initialization.
#
# You can uncomment this on non-Windows
# systems after creating a dedicated user.
;user openvpn
;group openvpn

# The persist option will try to avoid
# accessing certain resources on restart
# that may no longer be accessible because
# of the privilege downgrade.
persist-tun

# Output a short status file showing current connections, truncated and rewritten every minute.
status /var/log/openvpn/openvpn-status.log

log         /var/log/openvpn/openvpn.log
verb 4

#Silence repeating messages, 20 of the same ones here
#mute 20

# Notify the client that when the server restarts so it
# can automatically reconnect.
explicit-exit-notify 1


############################################################################### Crypto Settings
ca ajrxrootCA.pem
cert cert.pem
key key.pem

# You can always add the  AES-256-CBC cipher for backwards compatability
data-ciphers AES-256-GCM:AES-128-GCM:?CHACHA20-POLY1305

# Allow multiple client connections from the same CN
;duplicate-cn

# TLS auth key for HMAC
tls-auth ta.key 0 # This file is secret
tls-version-min 1.2
auth SHA512

# DH Parameters
dh none
ecdh-curve prime256v1

############################################################################### Network Settings
topology subnet

# Network to pull client addresses from
server 10.8.0.0 255.255.255.0

# Maintain a record of client <-> virtual IP address
# associations in this file.  If OpenVPN goes down or
# is restarted, reconnecting clients can be assigned
# the same virtual IP address from the pool that was
# previously assigned.
ifconfig-pool-persist /var/log/openvpn/ipp.txt

# Push routes to clients
push "route 10.8.0.0 255.255.255.0"
;push "route 192.168.20.0 255.255.255.0"

# If enabled, this directive will configure
# all clients to redirect their default
# network gateway through the VPN, causing
# all IP traffic such as web browsing and
# DNS lookups to go through the VPN
# (The OpenVPN server machine may need to NAT
# or bridge the TUN/TAP interface to the internet
# in order for this to work properly).
;push "redirect-gateway def1 bypass-dhcp"

#Allow client to client communication
;client-to-client

keepalive 10 120

max-clients 100




